package:
    name: cam_server_client
    version: 4.4.6

source:
    path: ..

requirements:
  build:
      - python
  run:
      - python
      - requests
      - bsread >1.5.1

build:
  number: 0

about:
    home: https://github.com/paulscherrerinstitute/cam_server
