package:
    name: cam_server_client
    version: "{{ load_setup_py_data().version }}"

source:
    path: ..

requirements:
  build:
      - python
  run:
      - python
      - requests
      - bsread >1.5.1

build:
  noarch: python
  number: 0

about:
    home: https://github.com/paulscherrerinstitute/cam_server
