FROM continuumio/miniconda3:4.6.14
    RUN conda install -c paulscherrerinstitute python=3.6 cam_server=3.6.0 && conda clean --all
 /Users/gobbo_a/dev/cam_server/conda-recipe/meta.yaml/Users/gobbo_a/dev/cam_server/ansible/install.yml