FROM continuumio/miniconda3:4.6.14
    RUN conda install -c paulscherrerinstitute -c conda-forge python=3.8 cam_server=5.1.7 scikit-image jungfrau_utils=3.5.0 && conda clean --all  && apt-get update && apt-get -y install vim

