package:
    name: cam_server
    version: 2.0.2

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - requests
        - bsread >=0.9.4
        - bottle
        - numpy
        - scipy
        - pyepics
        - matplotlib
        - pillow

build:
  entry_points:
    - camera_server = cam_server.start_camera_server:main
    - pipeline_server = cam_server.start_pipeline_server:main

about:
    home: https://git.psi.ch/controls_highlevel_applications/cam_server
