package:
    name: cam_server
    version: version: "{{ load_setup_py_data().version }}"

source:
    path: ..

requirements:
  build:
      - python
  run:
      - python
      - requests
      - bottle
      - psutil
      - paste
      - cheroot
      - numpy
      - scipy
      - numba
      - bitshuffle >=0.3.6.1
      - pyepics
      - h5py
      - jungfrau_utils
      - bsread >1.5.1
      - pillow
      - matplotlib
      - scikit-image
      - redis

build:
  number: 0
  entry_points:
    - camera_server = cam_server.start_camera_server:main
    - camera_proxy = cam_server.start_camera_proxy:main
    - camera_worker = cam_server.start_camera_worker:main
    - camera_manager = cam_server.start_camera_manager:main
    - pipeline_server = cam_server.start_pipeline_server:main
    - pipeline_proxy = cam_server.start_pipeline_proxy:main
    - pipeline_worker = cam_server.start_pipeline_worker:main
    - pipeline_manager = cam_server.start_pipeline_manager:main
    - validate_configs = cam_server.validate_configs:main
    - writer = cam_server.writer:main
    - bs = cam_server.start_bs:main

about:
    home: https://github.com/paulscherrerinstitute/cam_server


