- hosts: cam_workers
  become: true

  tasks:
   - name: Install filebeat
     command: yum -y install filebeat

   - name: Install metricbeat
     command: yum -y install metricbeat

   - name: Copy cert file
     command: wget http://elkmgt01.psi.ch/psi-elk-ca-cert.pem -P /etc/pki/CA/certs/

   - name: Create filebeat configuration file
     template: src=./templates/filebeat.yml dest=/etc/filebeat/filebeat.yml owner=root group=root mode=0644

   - name: Create metricbeat configuration file
     template: src=./templates/metricbeat.yml dest=/etc/metricbeat/metricbeat.yml owner=root group=root mode=0644

   - name: start filebeat service
     systemd:
        name: filebeat
        enabled: yes
        state: reloaded
        daemon_reload: yes

   - name: start metricbeat service
     systemd:
        name: metricbeat
        enabled: yes
        state: reloaded
        daemon_reload: yes


- hosts: cam_manager
  become: true

   - name: Install heartbeat
     command: yum -y install heartbeat-elastic

   - name: Create heartbeat configuration file
     template: src=./templates/heartbeat.yml dest=/etc/heartbeat/heartbeat l owner=root group=root mode=0644

   - name: start heartbeat service
     systemd:
        name: heartbeat-elastic
        enabled: yes
        state: reloaded
        daemon_reload: yes
