- hosts: cam_workers
  become: true

  tasks:
    - name: Copy script to remote machine
      copy:
        src: install_dockerless.sh
        dest: /tmp/install_dockerless.sh
        mode: 0755

    - name: Run script on remote machine
      script: /tmp/install_dockerless.sh

