- hosts: cam_workers
  become: true

  vars:
    bsrep: bsrep-0.4.1-amd64-rhel7
  tasks:
   - name: Download file using curl
     get_url:
       url: https://data-api.psi.ch/distri/{{bsrep}}.tgz
       dest: /cam_server_configuration/{{bsrep}}.tgz
       owner: root
       group: root
       mode: 0644

   - name: Creates bsrep folder
     file: path=/cam_server_configuration/bsrep state=directory

   - name: Unzip tar file
     unarchive:
       src: /cam_server_configuration/{{bsrep}}.tgz
       dest: /cam_server_configuration
       remote_src: yes
       owner: root
       group: root
       mode: 0644

   - name: Create bsrep folder if does not exist
     command: mkdir -p /cam_server_configuration/bsrep

   - name: Copy new files
     shell: cp /cam_server_configuration/{{bsrep}}/* /cam_server_configuration/bsrep/

   - name: Delete zip folder
     command: rm -r /cam_server_configuration/{{bsrep}}

   - name: Delete zip file
     command: rm -r /cam_server_configuration/{{bsrep}}.tgz

   - name: Create systemd config file
     template: src=../docker/repeater.service dest=/etc/systemd/system/repeater.service owner=root group=root mode=0644

   - name: Reload systemd Config
     shell: |
       systemctl daemon-reload

   - name: enable repeater service
     systemd:
       name: repeater
       enabled: yes
       daemon_reload: yes
