- hosts: cam_workers
  become: true

  vars:
    bsrep: bsrep-0.4.3-amd64-rhel7
  tasks:
   - name: Download file using curl
     get_url:
       url: https://data-api.psi.ch/distri/{{bsrep}}.tgz
       dest: /cam_server_configuration/{{bsrep}}.tgz
       owner: root
       group: root
       mode: 0644

   - name: Unzip tar file
     unarchive:
       src: /cam_server_configuration/{{bsrep}}.tgz
       dest: /cam_server_configuration
       remote_src: yes
       owner: root
       group: root
       mode: 0755

   - name: stop repeater
     systemd:
       name: repeater
       state: stopped

   - name: Copy new files
     shell: cp /cam_server_configuration/{{bsrep}}/* /cam_server_configuration/bsrep/

   - name: Delete zip folder
     command: rm -r /cam_server_configuration/{{bsrep}}

   - name: Delete zip file
     command: rm -r /cam_server_configuration/{{bsrep}}.tgz


   - name: start repeater
     systemd:
        name: repeater
        state: started

